name: selftest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 
        uses: actions/checkout@v3
      - uses: ./
        with:
          apikey: ${{ secrets.APIKEY }}
          target: ${{ secrets.TARGET }}
